### ISSUE TITLE
12/1[後台] 有入金申請時發出聲音提示

### ISSUE THREAD

**Issue by smbet7** [j7-dev/F22-FE#164]
(1) 有入金申請時發出聲音提示
(2) 讓工作人員可以上傳音檔
(3) 讓工作人員可以開關此功能

![90CE780B-71F1-49D4-9339-CFC1D84DCDA0](https://github.com/j7-dev/F22-FE/assets/149597872/b79d4b64-46b8-495b-8a77-1e0cbf4845b5)

**Comment by j7-dev** [comment]
pending 1 以上會變改底色
聲音的話  1以上 或  有變化  會跳提示音

![image](https://github.com/j7-dev/F22-FE/assets/9213776/3567ee38-be37-4653-8395-c7e73af54356)
